#!/usr/bin/env perl

BEGIN {
  if (!$::ENV{'BUILD_DIR'} && $0 ne '-' && $0 ne '-e' && -e $0 && ! -e '/etc/build.conf') {
    use Cwd ();
    my $p = Cwd::abs_path($0);
    $::ENV{'BUILD_DIR'} = $p if $p =~ s/\/[^\/]+$// && $p ne '/usr/lib/build' && -d "$p/PBuild";
  }
  unshift @INC, ($::ENV{'BUILD_DIR'} && ! -e '/etc/build.conf' ? $::ENV{'BUILD_DIR'} : '/usr/lib/build');
}

use strict;
use warnings;
use Mojo::Util qw(sha1_sum steady_time);

use Mojo::File qw(curfile path);
use lib curfile->dirname->sibling('lib')->to_string;
use Mojolicious::Commands;

my $cfg = path->sibling('pbuild_status.yml');
if (! -e $cfg) {
	open my $fh, '>', $cfg or die "$!\n";
	print $fh  "---\n";
	print $fh  "secrets:\n";
	print $fh  "  - " . sha1_sum($$ . steady_time . rand) . "\n";
	close $fh;
	print "wrote $cfg\n";
}

# Start command line interface for application
Mojolicious::Commands->start_app('PBuildStatus');
